# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Logger-Simple
version:      1.09
version_from: Simple.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Fcntl:                         0
    FileHandle:                    0
    Test::Harness:                 0
    Test::More:                    0
    Test::Pod:                     0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
